config/routes.rb
Trenda::Application.routes.draw do

  root 'pins#index'
  match '/auth/:provider/callback', to: 'sessions#create', via: 'get', as: 'login'
  match '/auth/failure', to: redirect('/'), via: 'get'
  delete 'logout' => 'sessions#destroy'
  get 'signup' => 'users#new'
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
  get 'faq' => 'pages#faq'
  get 'tos' => 'pages#tos'
  get 'privacy' => 'pages#privacy'
  post 'signup' => 'users#create'
  resources :users
  resources :pins do
    member do
      put "like" => "pins#like"
      put "dislike" => "pins#dislike"
    end
  end
end

app/models/pin.rb
class Pin < ActiveRecord::Base
  
  self.per_page = 20
  acts_as_votable
  belongs_to :user
  validates :title, presence: true
  validates :content, length: { maximum: 1500 }
  has_attached_file :photo, styles: { large: "500x500>", thumb: "220x220>" }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
  # validate :is_picture

  def self.search(search)
    where("title LIKE ? OR content LIKE ?", "%#{search}%", "%#{search}%") 
  end

  # Prettifies the URLs
  def to_param
    "#{id} #{title[0,30]}".parameterize
  end

  private

    # Validates the size of an uploaded picture.
    # def picture_size
    #   if picture.size > 5.megabytes
    #     errors.add(:picture, "should be less than 5MB")
    #   end
    # end

    # def is_picture
    #   errors.add(:picture, "format is invalid.") unless %w(image/jpeg image/png image/jpg image/gif image/tiff image/bmp).include? picture.sanitized_file.content_type
    # end

    # def is_picture
    #   unless picture.blank?
    #     unless %w(image/jpeg image/png image/jpg image/gif image/tiff image/bmp).include? picture.sanitized_file.content_type
    #       errors.add(:picture, "format is invalid.")
    #     end
    #   end
    # end

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController

  before_action :logged_in_user, except: [:index, :show]
  before_action :set_pin, except: [:index, :new, :create]
  before_action :correct_pin, only: [:destroy, :edit, :update]

  def index
    current_page = params[:page] || 1
    per_page = params[:per_page] || 16
    @pins = Pin.order('cached_votes_score DESC')

    if params[:search] && !params[:search].blank?
      @pins = Pin.search(params[:search])
      users = User.search(params[:search])
      unless users.blank?
        users.each do |user|
          @pins += user.pins
        end
      end
    end

    length = @pins.length

    @pins = WillPaginate::Collection.create(current_page, per_page, length) do |pager|
      pager.replace @pins[pager.offset, pager.per_page].to_a
    end
  end

  def show
    user = @pin.user.id    
		@pins = Pin.where(user_id: user).shuffle[0..7]
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin }
        format.json { render action: 'show', status: :created, location: @pin }
      else
        format.html { render action: 'new' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    if @pin.update(pin_params)
      flash[:success] = 'Post updated.'
      redirect_to @pin
    else
      render :edit
    end
  end

  def like
    @pin.liked_by current_user
    respond_to do |format|
      format.html {redirect_to :back}
      format.js
    end
  end

  def dislike
    @pin.disliked_by current_user
    respond_to do |format|
      format.html {redirect_to :back}
      format.js
    end
  end

  def destroy
    if @pin.destroy
      flash[:success] = 'Post deleted.'
      redirect_to current_user
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end
    
    def correct_pin
      @pin = current_user.pins.find_by(id: params[:id])      
      if @pin.nil?
        flash[:danger] = 'Unauthorised action!'
        redirect_to root_url
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:content, :title, :photo, :user_id)
    end
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>

  <div class="row">
    <div class="col-sm-10 col-sm-offset-1">  

      <% if @pin.errors.any? %>
      <div class="alert alert-danger">
        <ul>
          <% @pin.errors.full_messages.each do |msg| %>
            <li class="nunito danger"><%= msg %></li>
          <% end %>
        </ul>
        </div>
      <% end %>

      <div class="col-sm-6">
          <div class="form-group">
              <label class="nunito" for="email">Title* (You must enter a title)</label>
              <%= f.text_field :title, class: 'form-control', id: "pin-title" %>
          </div>
      </div>

      <div class="col-sm-6">
        <div class="form-group">
          <label class="nunito" for="subject">Picture</label>
          <button type="button" class="form-control btn btn-default" id="img_button">
            <i class="fa fa-picture-o"></i>Choose File
          </button>
          <%= f.file_field :photo, id: "img_file" %>
        </div>
      </div>

      <!-- <div class="col-sm-12">
        <div class="form-group">
          <button type="submit" class="btn btn-default"><i class="fa fa-picture-o"></i>Upload</button>
        </div>
      </div> -->

      <div class="col-sm-12">
        <div class="form-group">
          <label class="nunito" for="message">Message OR Website Address* (1400 characters or less)</label>
          <%= f.text_area :content, rows: 9, class: 'form-control', id: "pin-content" %>
        </div>
      </div>

       <div class="col-sm-12">
        <div class="form-group">
          <i class="badge" id="char-count">0</i>
        </div>
      </div>

      <div class="col-sm-12 text-center">
        <%= f.submit "Publish", class: "btn btn-primary", id: "trenda-btn", style: "margin-bottom: 30px;" %>
      </div>
    </div>
  </div>
  <!-- /.row -->
<% end %>

app/views/pins/_pin.html.erb
<div class="box panel panel-default">
  <%= link_to image_tag(pin.photo.url(:large), class: "pin-img img-responsive"), pin unless pin.photo.blank? %>
  <div class="panel-body">
    <span class="nunito">By</span> 
    <% if pin.user.provider == 'facebook' %>
    	<%= link_to pin.user.name, pin.user, class: "bold mclaren fblue" %>
    <% elsif pin.user.provider == 'linkedin' %>
      <%= link_to pin.user.name, pin.user, class: "bold mclaren lgray" %> 
    <% else %>
    	<%= link_to pin.user.name, pin.user, class: "bold mclaren tblue" %>
    <% end %>
    <h4 class="bold nunito"><%= link_to pin.title, pin, class: "wwrap" %></h4>
    <p>
    	<%= simple_format(pin.content[0,140], html_options = {class: "wwrap bitter"}) %>...
    </p>
    
  </div> <!--panel-body-->

  <div class="btn btn-group">   
	  <% if logged_in? %>
	    <%= link_to like_pin_path(pin), class: "btn btn-primary left-btn right-btn", method: :put, :remote => true do %>
	      <i class="fa fa-thumbs-up" aria-hidden="true"></i>
	      <i id="likes_count_<%= pin.id %>" class="badge"><%= pin.get_likes.size %></i>
	    <% end %>
	    <%= link_to dislike_pin_path(pin), class: "btn btn-primary left-btn right-btn", method: :put, :remote => true do %>
	      <i class="fa fa-thumbs-down" aria-hidden="true"></i>
	      <i  id="dislikes_count_<%= pin.id %>" class="badge"><%= pin.get_dislikes.size %></i>
	    <% end %>
	  <% end %>
	</div>

</div> <!--box-->

app/views/pins/_side_bar.html.erb
<br/>
<br/>
<div class="container-fluid">
  <div class="col-md-8 col-md-offset-2">
    <h2 class="bold black nunito text-center">More from <%= @pin.user.name %> </h2>
    <div id="pins">
      <% @pins.each do |pin| %>
        <div class="box-sm panel panel-default">
          <%= link_to image_tag(pin.photo.url(:thumb)), pin unless pin.photo.blank? %>
          <div class="panel-body">
            <h5 class="bold mclaren"><%= link_to pin.title, pin, style: "word-wrap: break-word;" %></h5>
          </div> <!--panel-body-->
        </div> <!--box-->
      <% end %>
    </div> <!--pins-->
  </div> <!--col-md-8-->
</div> <!--container-fluid-->

app/views/pins/dislike.js.erb
$("#dislikes_count_<%= @pin.id %>").html('<%= @pin.cached_votes_down %>');
$("#likes_count_<%= @pin.id %>").html('<%= @pin.cached_votes_up %>');
$("#dislikes_count_<%= @pin.id %>").hide().fadeIn(2000);

app/views/pins/edit.html.erb
<div id="all">

<div id="content">
  <div class="container">

    <div class="col-md-12">
      <ul class="breadcrumb">

          <li><%= link_to 'Home', root_path %></li>
          <li>Edit</li>
      </ul>
      
      <hr>

      <h2 class='text-center'>Edit</h2>
      
      <%= render 'form' %>

      </div>
      <!-- /#contact -->
    </div>

  </div>
  <!-- /.container -->
</div>
<!-- /#content -->

<%= javascript_include_tag 'pins' %>

app/views/pins/index.html.erb
<div class="container-fluid">
  <% flash.each do |message_type, message| %>
    <div class="nunito alert alert-<%= message_type %> col-md-6 col-md-offset-3">
      <%= message %>
    </div>
  <% end %>
  <div class="col-md-10 col-md-offset-1">
    <% unless @pins.blank? %>
      <div id="pins">
        <%= render @pins %>
      </div> <!--pins-->
      <div class="text-center">
        <%= will_paginate @pins, renderer: BootstrapPagination::Rails %>
      </div>
    <% else %>
      <div class="alert alert-warning col-md-6 col-md-offset-3">
        <h4 class="nunito">Nothing trending.</h4>
      </div>
    <% end %>
  </div> <!--col-md-10-->
</div> <!--container-fluid-->

app/views/pins/like.js.erb
$("#likes_count_<%= @pin.id %>").html('<%= @pin.cached_votes_up %>');
$("#dislikes_count_<%= @pin.id %>").html('<%= @pin.cached_votes_down %>');
$("#likes_count_<%= @pin.id %>").hide().fadeIn(2000);

app/views/pins/new.html.erb
<div id="all">

  <div id="content">
    <div class="container">

      <div class="col-md-12">
        <ul class="breadcrumb">

            <li><%= link_to 'Home', root_path %></li>
            <li> Publish </li>
        </ul>
        
        <hr>
        <h2 class='text-center'>Trenda It!</h2>

        <%= render 'form' %>
      </div>
      <!-- /#contact -->
    </div>
  </div>
  <!-- /.container -->
</div>
<!-- /#content -->

<%= javascript_include_tag 'pins' %>

app/views/pins/show.html.erb
<div class="container breathe">
  <% flash.each do |message_type, message| %>
    <div class="nunito alert alert-<%= message_type %> col-md-8 col-md-offset-2">
      <%= message %>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-7 col-md-offset-2">

      <ul class="media-list">
        <li class="media">
          <div class="media-left">
            <%= link_to @pin.user do %>
              <%= image_tag(@pin.user.avatar, class: "media-object img-circle pull-left", width: 50, height: 50) %>
            <% end %>
          </div>
          <div class="media-body">
            <h4 class="media-heading" style="padding: 10px;">
              <% if @pin.user.provider == 'facebook' %>
                <%= link_to @pin.user.name, @pin.user, class: "bold mclaren fblue" %>
              <% elsif @pin.user.provider == 'linkedin' %>
                <%= link_to @pin.user.name, @pin.user, class: "bold mclaren lgray" %> 
              <% else %>
                <%= link_to @pin.user.name, @pin.user, class: "bold mclaren tblue" %>
              <% end %>
            </h4>
            <div class="panel panel-default">
              <%= image_tag @pin.photo.url(:large), class: "img-responsive img-show top-left" unless @pin.photo.blank? %>
              <div class="panel-body">                   
                <% if @pin.content.downcase.start_with?('http') %>
                  <h3 class="bold black nunito text-left"><%= link_to @pin.title, @pin.content, target: "_blank", style: "word-wrap: break-word;" %></h3>
                <% elsif @pin.content.downcase.start_with?('www.') %>
                  <% url = @pin.content.gsub(@pin.content[0..3],"http://" ) %>
                  <h3 class="bold black nunito text-left"><%= link_to @pin.title, url, target: "_blank" %></h3>
                <% else %>
                  <h3 class="bold black nunito text-left"><%= @pin.title %></h3>
                <% end %>
                <span id="article">                  
                  <%= simple_format(@pin.content, html_options = {class: "wwrap bitter"}) %>
                </span>
                <br/>
                <span class="actions">
                  <% if logged_in? %>
                    <%= link_to like_pin_path(@pin), class: "btn btn-primary right-btn left-btn", method: :put, :remote => true do %>
                      <i class="fa fa-thumbs-up" aria-hidden="true"></i>
                      <i id="likes_count_<%= @pin.id %>" class="badge"><%= @pin.get_likes.size %></i>
                    <% end %>
                    <%= link_to dislike_pin_path(@pin), class: "btn btn-primary right-btn left-btn", method: :put, :remote => true do %>
                      <i class="fa fa-thumbs-down" aria-hidden="true"></i>
                      <i  id="dislikes_count_<%= @pin.id %>" class="badge"><%= @pin.get_dislikes.size %></i>
                    <% end %>
                  <% end %>
                  <% if current_user?(@pin.user) %>
                    <%= link_to edit_pin_path(@pin), class: "btn btn-primary right-btn left-btn" do %>
                      <i class="fa fa-edit" aria-hidden="true"></i>
                    <% end %>
                    <%= link_to @pin, class: "btn btn-danger right-btn left-btn", method: :delete, data: { confirm: "Are you sure you want to delete this trend?" } do %>
                      delete <i class="fa fa-trash" aria-hidden="true"></i>
                    <% end %>
                  <% end %>
                </span>
              </div>
            </div>
          </div>
        </li>
      </ul>

    </div>
    <!-- col-md-7 -->
  </div>
  <!-- row -->
</div>
<!-- container -->