config/routes.rb
Trenda::Application.routes.draw do

  root 'pins#index'
  match '/auth/:provider/callback', to: 'sessions#create', via: 'get', as: 'login'
  match '/auth/failure', to: redirect('/'), via: 'get'
  delete 'logout' => 'sessions#destroy'
  get 'signup' => 'users#new'
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
  get 'faq' => 'pages#faq'
  get 'tos' => 'pages#tos'
  get 'privacy' => 'pages#privacy'
  post 'signup' => 'users#create'
  resources :users
  resources :pins do
    member do
      put "like" => "pins#like"
      put "dislike" => "pins#dislike"
    end
  end
end

app/views/layouts/_footer.html.erb
<!-- *** FOOTER ***
_________________________________________________________ -->

<div id="footer">
  <div class="container">
    <div class="col-sm-3">
      <h4>Pages</h4>

      <ul>
          <li style="display: none;"><%= link_to "About", about_path %></li>
          <li><%= link_to "Contact", contact_path %></li>
          <li style="display: none;"><%= link_to "FAQ", faq_path %></li>
          <li><%= link_to "Terms of Service", tos_path %></li>
          <li><%= link_to "Privacy", privacy_path %></li>
          
      </ul>
    </div>
    <!-- /.col-sm-3 -->

    <div class="col-sm-3">

      <h4>User section</h4>
      <ul>
        <% unless logged_in? %>
          <li><%= link_to "Sign in with Facebook", "auth/facebook" %></li>
          <li><%= link_to "Sign in with LinkedIn", "auth/linkedin" %></li>
          <li><%= link_to "Sign in with Twitter", "auth/twitter" %></li>
        <% else %>
          <li><%= link_to "Publish", new_pin_path %></li>
        <% end %>
      </ul>


    </div>
    <!-- /.col-sm-3 -->

    <div class="col-sm-3">

      <h4>How to reach us</h4>

      <p><strong>Trenda.me</strong>
        <br>Email: <span style="color: color: #c27baa;">Lani@trenda.me</span>
        <br>Phone: <span style="color: color: #c27baa;">+2348023908727</span>
      </p>

      <hr class="hidden-md hidden-lg hidden-sm">

    </div>
    <!-- /.col-sm-3 -->

    <div class="col-sm-3">
      <%= form_tag(root_path, method: "get") do %>
        <div class="input-group">
          <%= text_field_tag :search, params[:search], class: "form-control" %>
          <i class="input-group-btn">
          	<%= button_tag(type: "submit", class: "btn btn-default") do %>
          		Search
            <% end %>
					</i>
        </div>
      <% end %>

    </div>
    <!-- /.col-sm-3 -->
  </div>
  <!-- /.container -->
</div>
<!-- /#footer -->

<!-- *** FOOTER END *** -->

<!-- *** COPYRIGHT ***
_________________________________________________________ -->

<div id="copyright">
  <div class="container">
    <div class="col-md-12">
    	<p class="pull-left">&copy; 2016, Trenda.me.</p>
    </div>
  </div>
</div>
<!-- /#copyright -->

<!-- *** COPYRIGHT END *** -->

app/views/layouts/_navbar.html.erb
<!-- *** NAVBAR ***
_________________________________________________________ -->

<div class="navbar navbar-default navbar-fixed-top yamm" role="navigation" id="navbar">
    <div class="container">
        <div class="navbar-header">

            <%= link_to root_path, class: "navbar-brand home" do %>
                <img src="<%= asset_path 'logo.png' %>" alt="Trenda logo" class="hidden-xs hidden-sm">
                <img src="<%= asset_path 'logo-small.png' %>" alt="Trenda logo" class="visible-xs visible-sm">
                <span class="sr-only">Trenda - go to homepage</span>
            <% end %>
            <div class="navbar-buttons">
                <button type="button" class="navbar-toggle btn-primary" data-toggle="collapse" data-target="#navigation">
                    <span class="sr-only">Toggle navigation</span>
                    <i class="fa fa-align-justify"></i>
                </button>
                <button type="button" class="navbar-toggle btn-default" data-toggle="collapse" data-target="#search">
                    <span class="sr-only">Toggle search</span>
                    <i class="fa fa-search"></i>
                </button>

            </div>
        </div>
        <!--/.navbar-header -->

        <div class="navbar-collapse collapse" id="navigation">

          <ul class="nav navbar-nav navbar-left">
            <li class="active dropdown normal-dropdown">
              <%= link_to root_path do %>
                <i class="fa fa-home"></i>
              <% end %>
            </li>            
            <li class="active dropdown normal-dropdown">
              <%= link_to contact_path do %>
                Contact <i class="fa fa-phone"></i>
              <% end %>
            </li>
            <% if logged_in? %>
              <li class="active dropdown normal-dropdown">
                <%= link_to "Publish", new_pin_path, class: "mclaren" %>
              </li>
              <li class="active dropdown normal-dropdown">
                <%= link_to current_user do %>
                  <%= image_tag(current_user.avatar, class: "img-circle", width: 30, height: 30) %>
                <% end %>
              </li>
              <li class="active dropdown normal-dropdown">
                <%= link_to "Sign Out", logout_path, class: "mclaren", method: :delete %>
              </li>
            <% else %>
              <li class="active dropdown normal-dropdown">
                <%= link_to '/auth/facebook', class: "mclaren" do %>
                  Sign In <i class="fa fa-facebook-square"></i>
                <% end %>
              </li>
              <li class="active dropdown normal-dropdown">
                <%= link_to '/auth/linkedin', class: "mclaren" do %>
                  Sign In <i class="fa fa-linkedin-square"></i>
                <% end %>
              </li>
              <li class="active dropdown normal-dropdown">
                <%= link_to '/auth/twitter', class: "mclaren" do %>
                  Sign In <i class="fa fa-twitter-square"></i>
                <% end %>
              </li>
            <% end %>
          </ul>

        </div>
        <!--/.nav-collapse -->

        <!-- <div class="navbar-collapse collapse right" id="basket-overview">
            <a href="basket.html" class="btn btn-primary navbar-btn">
            	<i class="fa fa-shopping-cart"></i>
          		<span class="hidden-sm">3 items
          			<span class="hidden-md">in cart</span>
          		</span>
          	</a>
        </div> -->

        <!--/.nav-collapse -->

        <div class="navbar-collapse collapse right">
            <button type="button" class="btn navbar-btn btn-default" data-toggle="collapse" data-target="#search">
                <span class="sr-only">Toggle search</span>
                <i class="fa fa-search"></i>
            </button>
        </div>

        <div class="navbar-collapse collapse right">
          <%= link_to new_pin_path do %>
            <button type="button" class="btn navbar-btn btn-primary">
              <i class="fa fa-pencil"></i>
            </button>
          <% end %>
          <%= link_to root_path do %>
            <button type="button" class="btn navbar-btn btn-primary">              
              <i class="fa fa-home"></i>
            </button>
          <% end %>
        </div>

        <div class="collapse clearfix" id="search">

          <%= form_tag(root_path, method: "get", class: "navbar-form") do %>
            <div class="input-group">
              <%= text_field_tag :search, params[:search], placeholder: "Search", class: "nunito form-control" %>
              <span class="input-group-btn">
			      		<%= button_tag(type: "submit", class: "btn btn-primary") do %>
			      			<i class="fa fa-search"></i>
                <% end %>
			        </span>
            </div>
          <% end %>

        </div>
        <!--/.nav-collapse -->

    </div>


</div>
<!-- /#navbar -->

<!-- *** NAVBAR END *** -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="google-site-verification" content="72eS_Y1zv3_b8iOMOsp3X1g9iEqtmLck6LJOAcczLe4" />
    <meta name="author" content="AGABA, Philip">

    <%= favicon_link_tag(source='favico.png', options={}) %>
    
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
  	
  	<%= render 'layouts/navbar' %>
  	
  	<!-- flash ordinarily goes here -->
    <% if @user %>
      <div class="col-sm-4 col-sm-offset-3">
        <ul class="media-list">
          <li class="media">
            <div class="media-left">
              <%= image_tag(@user.avatar, class: "media-object img-circle pull-left", width: 50, height: 50) %>
            </div>
            <div class="media-body">
              <span class="bubble me">
                <h3 class="media-heading" style="padding: 10px;">
                  <span class="mclaren" style="font-size: .8em">I am </span>
                  <% if @user.provider == 'facebook' %>
                    <span class="fblue nunito"><%= @user.name %></span>
                  <% elsif @user.provider == 'linkedin' %>
                    <span class="lgray nunito"><%= @user.name %></span>
                  <% else %>
                    <span class="tblue nunito"><%= @user.name %></span>
                  <% end %>
                </h3>
              </span>
            </div>
          </li>
        </ul>
      </div>
    <% end %>

  	<%= yield %>

    <div id="all" class="nunito">
      <%= render 'layouts/footer' %>
    </div>
  	
  </body>
</html>